// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKnlZf9dRJBGFSqLYYKs2Uh9D6-Apfg4k',
    appId: '1:703640946172:web:4d259a5ddacc2cff9b9e79',
    messagingSenderId: '703640946172',
    projectId: 'sistem-penjurian-burung-4d136',
    authDomain: 'sistem-penjurian-burung-4d136.firebaseapp.com',
    storageBucket: 'sistem-penjurian-burung-4d136.firebasestorage.app',
    measurementId: 'G-W3RNMBWRJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUPQezefYBoExQbLTWCAnVj0_Y7Gtil8',
    appId: '1:690732126998:android:6bb7b23cea18fb1281f637',
    messagingSenderId: '690732126998',
    projectId: 'penjurianburung-dd3af',
    storageBucket: 'penjurianburung-dd3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJo_CaIyyp1LH9438B08zN296uAOLa_Cs',
    appId: '1:703640946172:ios:fb8f4cc7a62581e29b9e79',
    messagingSenderId: '703640946172',
    projectId: 'sistem-penjurian-burung-4d136',
    storageBucket: 'sistem-penjurian-burung-4d136.firebasestorage.app',
    iosBundleId: 'com.example.sistem_penjurian_burung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJo_CaIyyp1LH9438B08zN296uAOLa_Cs',
    appId: '1:703640946172:ios:fb8f4cc7a62581e29b9e79',
    messagingSenderId: '703640946172',
    projectId: 'sistem-penjurian-burung-4d136',
    storageBucket: 'sistem-penjurian-burung-4d136.firebasestorage.app',
    iosBundleId: 'com.example.sistem_penjurian_burung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKnlZf9dRJBGFSqLYYKs2Uh9D6-Apfg4k',
    appId: '1:703640946172:web:7ab137b942a5c6ea9b9e79',
    messagingSenderId: '703640946172',
    projectId: 'sistem-penjurian-burung-4d136',
    authDomain: 'sistem-penjurian-burung-4d136.firebaseapp.com',
    storageBucket: 'sistem-penjurian-burung-4d136.firebasestorage.app',
    measurementId: 'G-ZJG1LZD56T',
  );
}
